
opponent_game_lines = [
    "By the power of the arcane, I summon forth my champion!",
    "Your feeble attempts are no match for my magical prowess.",
    "Prepare yourself for a battle you won't soon forget!",
    "Ah, another worthy adversary. Let the duel commence!",
    "You may have strength, but do you possess cunning?",
    "My deck holds secrets even the gods would envy.",
    "Beware, for my cards hold powers beyond comprehension.",
    "With every draw, my victory draws nearer.",
    "I sense fear in your eyes. Is it the fear of defeat?",
    "Your fate hangs by a thread. Will you dare to challenge it?",
    "Behold the might of the dragons I command!",
    "Through the darkness, my creatures emerge unscathed.",
    "Your spells are feeble compared to the magic I wield.",
    "Do you dare to challenge the master of illusions?",
    "The winds of fortune blow in my favor. Can you withstand them?",
    "Even in the face of despair, I will emerge victorious.",
    "My cards whisper tales of triumph and glory.",
    "In this realm, only the strong survive. Are you strong enough?",
    "A true warrior knows when to strike and when to bide their time.",
    "May the gods favor me in this battle. And may they forsake you.",
    "Well played, but luck won't save you for long.",
    "Impressive move, but it won't be enough to stop me.",
    "You're proving to be a worthy opponent.",
    "I see you're not going down without a fight.",
    "You've got potential, but you're still no match for me.",
    "Interesting strategy. Let's see how it holds up.",
    "You've made a good move, but can you keep it up?",
    "Nicely done. But can you handle what comes next?",
    "You're starting to impress me. Keep it up.",
    "A solid play. But will it be enough to turn the tide?",
    "You're holding your own, but I'm just getting started.",
    "You're not making this easy for me.",
    "Good move. But watch out, I'm just getting warmed up.",
    "You're making me work for this victory.",
    "You're putting up a good fight. I respect that.",
    "You're getting better with each turn.",
    "You're proving to be quite the challenge.",
    "Nice try, but I'm one step ahead of you.",
    "You're getting closer to victory, but so am I.",
    "You're making me sweat. Keep it up.",
    "You're making some interesting choices.",
    "You're not making it easy for me to win.",
    "You're making me rethink my strategy.",
    "You're keeping me on my toes. I like it.",
    "You're a formidable opponent, I'll give you that.",
    "You're making this game more interesting.",
    "You're making me work harder than I expected.",
    "You're holding your own, but can you keep it up?",
    "You're proving to be a challenge. I like that.",
    "You're making me think twice about my moves.",
    "You're not going down without a fight. I respect that.",
    "You're making me earn this victory.",
    "You're showing some skill. But it won't be enough.",
    "You're making me work for every point.",
    "You're making me work harder than I anticipated.",
    "You're making me sweat. Keep it up.",
    "You're proving to be quite the strategist.",
    "You're giving me a run for my money.",
    "You're not going down without a fight. Admirable.",
    "Why did the wizard bring a ladder to the dungeon? Because he heard the stakes were high!",
    "What do you call a bard with a broken lute? A minor problem!",
    "Why did the rogue go to wizard school? He wanted to pick up some new spells!",
    "Why was the paladin always invited to parties? Because he was a real 'party' animal!",
    "What do you get when you cross a cleric with a barbarian? Someone who can heal you and then break you!",
    "How does a sorcerer keep their hair so neat? With a spell of course!",
    "Why don't necromancers ever get lost? Because they always know which way is 'deady'!",
    "What do you call a group of goblins on a road trip? A car-nage!",
    "Why did the elf refuse to play cards with the dwarf? Because he heard he was a cheater!",
    "How do you know if a dragon has been in your garden? Your vegetables are roasted!",
    "What's a vampire's favorite fruit? A blood orange!",
    "Why was the ranger always invited to picnics? Because he was great at 'bringing the bear'!",
    "What's a wizard's favorite type of music? Spell-binding melodies!",
    "Why did the cleric bring a shovel to the graveyard? To help 'raise' some spirits!",
    "Why did the rogue get kicked out of the thieves' guild? He stole their heart... literally!",
    "What do you call a goblin who's good at archery? A bull's-eye!",
    "Why did the bard get banned from the tavern? Because his jokes were too 'punny'!",
    "What do you call a group of adventurers who keep arguing? A 'dis'-cord party!",
    "Why was the necromancer always so lonely? Because he had a 'grave' personality!",
    "What do you get when you cross a dwarf with a canary? A miner bird!"

]

opponent_dead_lines = [
    "Well played. You were the better strategist today.",
    "I concede defeat. But remember, victory is fleeting.",
    "You've bested me this time. But the game isn't over yet.",
    "A valiant effort on your part. I shall retreat for now.",
    "Impressive. I must admit defeat, but I'll be back stronger.",
    "You've shown your prowess. I bow to your superiority.",
    "Defeat stings, but I congratulate you on your victory.",
    "Hats off to you. I've been outmaneuvered this time.",
    "You've proven your skill. Until we meet again, farewell.",
    "I must acknowledge your victory. May your reign be just.",
    "Well fought. Your victory is well deserved.",
    "You've conquered me fair and square. Until next time.",
    "My defeat is your triumph. Enjoy the spoils.",
    "You've emerged victorious. I shall concede defeat gracefully.",
    "Your strategy was flawless. I yield to your mastery."
]

opponent_victory_lines = [
    "Victory is mine! A well-earned triumph.",
    "The day is mine! A testament to my strategy.",
    "A glorious victory! None can stand against me.",
    "Behold, the victor stands tall! Glory is mine!",
    "I emerge triumphant! A master of the battlefield.",
    "Another victory secured! My dominance is unquestioned.",
    "A flawless victory! None can match my prowess.",
    "I am the champion! My name shall be remembered.",
    "The game is won! Victory belongs to me.",
    "The spoils of victory are mine to claim!",
    "Witness my triumph! None can challenge my skill.",
    "A decisive victory! None can dispute my superiority.",
    "I stand victorious! Bow before your conqueror.",
    "Behold, the vanquisher! None can withstand my might.",
    "My victory is absolute! None can deny my greatness."
]

opponent_opening_lines = [
    "Ah, a worthy adversary. Let the battle begin!",
    "Greetings, challenger. Prepare yourself for a duel!",
    "Welcome, brave soul. Shall we test our skills?",
    "Well met, traveler. Are you ready for a challenge?",
    "Greetings, fellow adventurer. Let's see who emerges victorious!",
    "Ah, another challenger approaches. Let the games commence!",
    "Welcome to the arena! May the best player prevail.",
    "Greetings, friend. Shall we engage in a battle of wits?",
    "Salutations! Are you prepared to face my formidable deck?",
    "Welcome, comrade. Let's see who has the stronger strategy.",
    "Greetings, foe. Prepare yourself for a fierce contest!",
    "Ah, a new opponent. Shall we see who has the sharper blade?",
    "Welcome to the battleground! Let the clash of cards begin!",
    "Greetings, rival. Are you ready to test your mettle?",
    "Well met, fellow warrior. Let's see who has the stronger will."
]
